[package]
name = "irr"
version = "0.0.1"
edition = "2024"
authors = ["Ashish Thomas <ashishthomassm@gmail.com>"]
license = "AGPL-3.0-or-later OR LicenseRef-Commercial"
description = "High-performance financial engine for IRR and borrowing computations. Built with Rust, Polars, and Arrow; featuring IFRS compliance, Zero-Copy architecture, and a SIMD-optimized Struct-of-Arrays (SoA) layout."
[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"
polars = { version = "0.53.0", features = [  "lazy", "strings", "timezones","semi_anti_join","cum_agg"] }
polars-arrow = "0.53.0"
rayon = "1.11.0"
thiserror = "2.0.17"
tokio = "1.49.0"

[target.'cfg(windows)'.dependencies]
mimalloc = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.6.1"

[profile.dev]
codegen-units = 20

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = 1
strip = "none"

[profile.profile]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = 2
strip = false
split-debuginfo = "packed"
