[package]
name = "irr"
version = "0.0.1"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
polars = { version = "0.53.0", features = [  "lazy", "strings", "timezones","semi_anti_join"] }
polars-arrow = "0.53.0"
rayon = "1.11.0"
thiserror = "2.0.17"
tokio = "1.49.0"

# Mimalloc only for Windows targets
[target.'cfg(windows)'.dependencies]
mimalloc = "0.1"

# Jemalloc only for Linux targets
[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.6.1"

[profile.dev]
codegen-units = 20

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
strip = true

[profile.profile]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = true
strip = false
