[package]
name = "irr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
env_logger = "0.11.8"
log = "0.4.29"
polars = { version = "0.52.0", features = [  "lazy", "strings", "timezones","semi_anti_join"] }
rayon = "1.11.0"
thiserror = "2.0.17"
tokio = "1.49.0"

[profile.dev]
codegen-units = 20
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false
strip = true
